### PR TITLE
Fix #78

### LINKED ISSUE #78: Wrong ASDF version loaded
I am not sure what is happening, but I cannot get my specified ASDF version loaded in Alive. When I test `sbcl` directly, I load ASDF-3.3.4, but when I launch it through sbcl, the version becomes `3.3.1`. This older version does not support `local-nicknames` so it is problematic for me.

### PR DESCRIPTION
**Pull request by rongcuid**
A fix for Unix-like system. This should work for SBCL on Unix and Cygwin, but I believe this will not work for SBCL on windows.

On Windows, the path separator is ';', but I don't know a way to determine how SBCL is built. I suppose either the extension parses the shell version into S-expr version, or we let the user specify it (adding a configuration).

Also, given that I have good experience with Alive with ABCL, we might need to consider their support too.

### CODE REVIEW

**Comment by rongcuid** [comment]
Apparently when I packaged and installed it Swank throws an error...

**Comment by nobody-famous** [comment]
Good find on this one. I'm hoping to have time this weekend to test the fix.

The colon should come from the path module. It's path.delimiter, maybe? Something like that. There's a constant that has the platform-specific path separator in that module somewhere.

**Comment by rongcuid** [comment]
Alive compiles Quicklisp every time I load it after this change. I don't know why this is the case.

**Comment by nobody-famous** [comment]
I'm thinking maybe setting that environment variable isn't the right approach. It's only being set so that it can find the downloaded version of swank. Loading swank from an absolute path or something might work better.

**Comment by rongcuid** [comment]
OK, I looked at Swank code and your implementation on `Load ASDF System`. The command sends `swank:reload-system`, which always triggers a recompile. 

Unfortunately, I don't find a slime function that does compiling on-demand...

File: src/vscode/commands/Repl.ts [hunk 1]
```diff
@@ -569,7 +569,7 @@ function getClSourceRegistryEnv(
 ): { [key: string]: string | undefined } {
     const updatedEnv = { ...processEnv }
     if (!processEnv.CL_SOURCE_REGISTRY) {
-        updatedEnv.CL_SOURCE_REGISTRY = slimePath
+        updatedEnv.CL_SOURCE_REGISTRY = slimePath + ":"
```
Comment (nobody-famous) [inline src/vscode/commands/Repl.ts:572]: Change to

        updatedEnv.CL_SOURCE_REGISTRY = slimePath + path.delimiter

**Review by nobody-famous — CHANGES_REQUESTED** [review]

File: src/vscode/commands/Repl.ts (hunk 1 above)
Comment (rongcuid) [reply src/vscode/commands/Repl.ts]: Done
